my_string = input()
print(len(my_string))
print(my_string.upper())
my_string = input()
print(my_string.lower())
my_string = input()
print(my_string.replace(' ',''))
my_string = input()
print(my_string[0].replace('',''))
my_string = input()
print(my_string[-1].replace('',''))